-- 1. CHO BIẾT MÃ CỦA CÁC GIÁO VIÊN CÓ HỌ TÊN BẮT ĐẦU LÀ “NGUYỄN” VÀ LƯƠNG TRÊN $2000, HOẶC GIÁO VIÊN LÀ TRƯỞNG BỘ MÔN NHẬN CHỨC SAU NĂM 1995.
SELECT
    MAGV
FROM GIAOVIEN
    JOIN BOMON ON GIAOVIEN.MAGV = BOMON.TRUONGBM
WHERE HOTEN LIKE N'NGUYỄN%'
    AND LUONG > 2000
    OR YEAR(NGAYNHANCHUC) > 1995

-- 2. VỚI MỖI GIÁO VIÊN, HÃY CHO BIẾT THÔNG TIN CỦA BỘ MÔN MÀ HỌ ĐANG LÀM VIỆC.
SELECT
    GIAOVIEN.MAGV,
    GIAOVIEN.HOTEN,
    BOMON.TENBM,
    BOMON.PHONG,
    BOMON.DIENTHOAI,
    BOMON.TRUONGBM,
    BOMON.MAKHOA,
    BOMON.NGAYNHANCHUC
FROM GIAOVIEN
    JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM

-- 3. CHO BIẾT TÊN GIÁO VIÊN LỚN TUỔI NHẤT CỦA BỘ MÔN HỆ THỐNG THÔNG TIN.
SELECT
    HOTEN
FROM GIAOVIEN
WHERE YEAR(NGSINH) IN (
    SELECT MIN(YEAR(NGSINH))
FROM GIAOVIEN
WHERE MABM = 'HTTT'
)

-- 4. CHO BIẾT HỌ TÊN GIÁO VIÊN CHỦ NHIỆM NHIỀU ĐỀ TÀI NHẤT
WITH
    SODETAI
    AS
    (
        SELECT
            GVCNDT,
            COUNT(GVCNDT) AS SL_DT
        FROM DETAI
        GROUP BY GVCNDT
    )
SELECT HOTEN
FROM GIAOVIEN
WHERE MAGV IN (
    SELECT
    GVCNDT
FROM SODETAI
WHERE SL_DT IN (
        SELECT
    MAX(SL_DT) AS MAX_SDT
FROM SODETAI
    )
)

-- 5. CHO BIẾT TÊN GIÁO VIÊN VÀ TÊN BỘ MÔN CỦA GIÁO VIÊN THAM GIA NHIỀU ĐỀ TÀI NHẤT.
WITH
    THAMGIADETAI
    AS
    (
        SELECT
            MAGV, COUNT(MAGV) AS SL_THAMGIADETAI
        FROM THAMGIADT
        GROUP BY MAGV
    )
SELECT
    HOTEN, TENBM
FROM GIAOVIEN
    JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM
WHERE MAGV IN (
    SELECT
    MAGV
FROM THAMGIADETAI
WHERE SL_THAMGIADETAI IN (
        SELECT
    MAX(SL_THAMGIADETAI) AS MAX_SL_THAMGIADETAI
FROM THAMGIADETAI
    )
)

-- 6. CHO BIẾT TÊN ĐỀ TÀI NÀO MÀ ĐƯỢC TẤT CẢ CÁC GIÁO VIÊN CỦA BỘ MÔN HTTT THAM GIA.
WITH
    SL_GV_HTTT
    AS
    (
        SELECT
            MADT,
            COUNT(DISTINCT MAGV) AS COUNT_GV
        FROM THAMGIADT
        WHERE MAGV IN (
        SELECT
            MAGV
        FROM GIAOVIEN
        WHERE MABM = 'HTTT'
    )
        GROUP BY MADT
    )
SELECT TENDT
FROM DETAI
WHERE MADT IN (
    SELECT
    MADT
FROM SL_GV_HTTT
WHERE COUNT_GV = (
        SELECT
    COUNT(MAGV)
FROM GIAOVIEN
WHERE MABM = 'HTTT'
    )
)

-- 7. CHO BIẾT TÊN GIÁO VIÊN NÀO ĐÃ THAM GIA TẤT CẢ CÁC ĐỀ TÀI CỦA DO TRẦN TRÀ HƯƠNG LÀM CHỦ NHIỆM.
SELECT
    HOTEN
FROM GIAOVIEN
WHERE MAGV IN (
    SELECT
    MAGV
FROM THAMGIADT
WHERE MADT IN (
        SELECT
    MADT
FROM DETAI
WHERE GVCNDT IN (
            SELECT
    MAGV
FROM GIAOVIEN
WHERE HOTEN = N'TRẦN TRÀ HƯƠNG'
        )
    )
)

-- 8. CHO BIẾT TÊN ĐỀ TÀI NÀO MÀ ĐƯỢC TẤT CẢ CÁC GIÁO VIÊN CỦA KHOA CNTT THAM GIA.
WITH
    SL_GV_KHOACNTT
    AS
    (
        SELECT
            MADT,
            COUNT(DISTINCT MAGV) AS COUNT_GV
        FROM THAMGIADT
        WHERE MAGV IN (
        SELECT
            MAGV
        FROM GIAOVIEN
            JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM
        WHERE MAKHOA = 'CNTT'
    )
        GROUP BY MADT
    )
SELECT
    TENDT
FROM DETAI
WHERE MADT IN (
    SELECT
    MADT
FROM SL_GV_KHOACNTT
WHERE COUNT_GV = (
        SELECT
    COUNT(MAGV)
FROM GIAOVIEN
    JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM
WHERE MAKHOA = 'CNTT'
    )
)

-- 9. CHO BIẾT TÊN ĐỀ TÀI NÀO MÀ ĐƯỢC TẤT CẢ CÁC GIÁO VIÊN CỦA KHOA SINH HỌC THAM GIA.
WITH
    SL_GV_KHOASH
    AS
    (
        SELECT
            MADT,
            COUNT(DISTINCT MAGV) AS COUNT_GV
        FROM THAMGIADT
        WHERE MAGV IN (
        SELECT
            MAGV
        FROM GIAOVIEN
            JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM
        WHERE MAKHOA = 'SH'
    )
        GROUP BY MADT
    )
SELECT
    TENDT
FROM DETAI
WHERE MADT IN (
    SELECT
    MADT
FROM SL_GV_KHOASH
WHERE COUNT_GV = (
        SELECT
    COUNT(MAGV)
FROM GIAOVIEN
    JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM
WHERE MAKHOA = 'SH'
    )
)

-- 10. CHO BIẾT MÃ SỐ, HỌ TÊN, TÊN BỘ MÔN VÀ TÊN NGƯỜI QUẢN LÝ CHUYÊN MÔN CỦA GIÁO VIÊN THAM GIA TẤT CẢ CÁC ĐỀ TÀI THUỘC CHỦ ĐỀ “NGHIÊN CỨU PHÁT TRIỂN”.
WITH
    GV_DT_NCPT
    AS
    (
        SELECT
            *
        FROM GIAOVIEN
        WHERE MAGV IN (
        SELECT
            MAGV
        FROM THAMGIADT
        WHERE MADT IN (
            SELECT
            MADT
        FROM DETAI
        WHERE MACD = 'NCPT'
        )
    )
    )
SELECT
    GV_DT_NCPT.MAGV,
    GV_DT_NCPT.HOTEN,
    BOMON.TENBM,
    GIAOVIEN.HOTEN
FROM GV_DT_NCPT
    LEFT JOIN GIAOVIEN ON GV_DT_NCPT.GVQLCM = GIAOVIEN.MAGV
    JOIN BOMON ON GV_DT_NCPT.MABM = BOMON.MABM
